### ISSUE TITLE
setup guide

### ISSUE THREAD

**Issue by dyay108** [mrc-g/ASK2HA#1]
was looking for a solution to enabling alexa to contorl my hass devices without having to expose hass to the web and came across your repo. A more complete setup guide would be greatly appreciated.

**Comment by mrc-g** [comment]
Yes, it is kind of difficult to setup. I don't even remember how to create the Alexa skill anymore.

Where do you find difficulties and think I should expand the documentation? Something is already explained in the haaska GitHub wiki, but I agree that some points in that guide is difficult to follow.

The setup in general start by following the haaska setup:
1) First you need to create the Alexa skill and configure it
2) Create the lambda function in AWS
3) Add the third party app in home assistant and configure  it

Instead in this setup the point 2 and 3 are slightly changed into point 4 and 6 (you can do the points in any order but you need to add the configuration later for the missing info):
2) create a dynamoDB table in AWS
3) create a SQS queue in AWS
4) create the lambda function in AWS (but with my code inside) and configure it with the table and the queue info
5) create an access token for home assistant to access AWS resources (table and queue)
6) add this app as third party in home assistant and configure it with the table/queue/access info

**Comment by dyay108** [comment]
I already have haaska setup or at least i followed home assistant's guide to get alexa working with hass entities. I have the skill setup and all. I really just needed clarification on where ask2ha comes in. Going to follow your instructions above and see if i can get it up and running. Btw, are you still using that setup?  I saw u mentioned in the forums how nothing has been breaking and the ask2ha required no maintenance after the initial development.

**Comment by mrc-g** [comment]
Yes, I'm still using it right now and working since the first setup. Around 2 years.

**Comment by mrc-g** [comment]
I hope to have clarified your doubts, inform me if anything else come up. I'm going to revise the readme at the end using the information on this issue.

**Comment by dyay108** [comment]
I greatly appreciate your efforts and you taking the time out to help out.

**Comment by mrc-g** [comment]
I added some details to the readme for now

**Comment by dyay108** [comment]
is alexa going to trigger the new lambda function?

EDIT: so i created a new alexa skill in the dev console and added the newly created lambda as the endpoint. I added Amazon Smarthome trigger to the newly created lambda and linked it to the new skill.

In the alexa app, when i  try to add the new skill, no devices are discovered. The lambda doesnt even generate any logs which lead me to believe it's not getting triggered. There were no entries in SQS either.

**Comment by mrc-g** [comment]
You can try 2 things:
First, you can look in the home assistant logs (the app logs) it should output only dots when is waiting "........." 1 for every pull request, if it receive a request from alexa it outputs the id of such request
Second, the lambda function does not output anything by default, only in case of errors, you can try add a print in the main function. Or you can search in the metrics of the lambda service (I can't find anywhere else log of the app, no trace no logs) as an indication that it was invoked.

**Comment by dyay108** [comment]
i did add a print statement to the lambda.
the add-on log output is just the last startup process it seems.

ask2ha log:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
start
2022-07-15 11:08:55.502000-05:00
0
>


hass log:

> 2022-07-15 12:12:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/alexa/smart_home_http.py", line 133, in post
response = await async_handle_message(
File "/usr/src/homeassistant/homeassistant/components/alexa/smart_home.py", line 21, in async_handle_message
assert request[API_DIRECTIVE][API_HEADER]["payloadVersion"] == "3"
TypeError: string indices must be integers

**Comment by mrc-g** [comment]
I don't understand, the ask2ha logs should contain something more, I'm not home right now so I can't check but I think that it should output dots or errors or "not a directive", exceptions etc

And seems like (from the logs of Hass) that something got to Hass

**Comment by mrc-g** [comment]
You need to update the configuration.yaml with the new data, client_id and client_secret.

See linking Alexa skill kit to login with Amazon on https://github.com/mike-grant/haaska/wiki/Setting-up-haaska

I think the problem is around there because the ask2ha logs indicate that the access to AWS, the queue and the table are correct. Also, something got to home assistant smart home service and failed (maybe ask2ha does not output anything because it receive a timeout and in the code it does not output anything with that exception).
This indicate that everything works fine but home assistant can't elaborate the requests.

**Comment by dyay108** [comment]
what's the flow?
Alexa skill triggers lambda which in turn enqueues the payload in SQS, then hass, which is checking the queue on an interval (using your add-on), dequeues the last item and performs whatever action was in that payload locally?

**Comment by dyay108** [comment]
replaying an event from the previously working haaka skill with your lambda works just fine. Seems like the new skill i setup just isnt triggering the lambda.

EDIT: Got it to work! missed the "Setup Account Linking" step from the haaka wiki.
Thank you for everything!

**Comment by mrc-g** [comment]
Yeah the flow is as you said (added the return that is as a record on the table and the Alexa skill get the answer from there).
